- hosts: terraform-ansible
  tasks:
    - name: instalando o python 3 e virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: instalando dependencias pip
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: alterando o hosts do settings
      linefiles:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
